---
all:
  vars:
    ansible_user: hpcadmin
    ansible_ssh_private_key_file: ~/.ssh/hpc_cluster
    cluster_name: onprem-hpc
    cluster_domain: hpc.local
    nfs_server: "{{ hostvars['controller01']['ansible_host'] }}"
    nfs_shared_home: /home
    nfs_shared_opt: /opt/hpc

  children:
    login:
      hosts:
        login01:
          ansible_host: 10.0.10.10

    controller:
      hosts:
        controller01:
          ansible_host: 10.0.10.11
          slurm_role: controller

    compute:
      vars:
        slurm_role: compute
      hosts:
        compute01:
          ansible_host: 10.0.10.20
          gpu_enabled: false
        compute02:
          ansible_host: 10.0.10.21
          gpu_enabled: false
        compute03:
          ansible_host: 10.0.10.22
          gpu_enabled: true
          gpu_type: nvidia
        compute04:
          ansible_host: 10.0.10.23
          gpu_enabled: true
          gpu_type: nvidia

    slurm_nodes:
      children:
        controller: {}
        compute: {}

    cluster:
      children:
        login: {}
        controller: {}
        compute: {}
